# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\nml_service\"8\n\rResumeRequest\x12\x13\n\x0bresume_text\x18\x01 \x01(\t\x12\x12\n\nprofession\x18\x02 \x01(\t\"\xb3\x01\n\x0eResumeResponse\x12\x41\n\x0c\x66inal_levels\x18\x01 \x03(\x0b\x32+.ml_service.ResumeResponse.FinalLevelsEntry\x12*\n\nevaluation\x18\x02 \x01(\x0b\x32\x16.ml_service.Evaluation\x1a\x32\n\x10\x46inalLevelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"U\n\nEvaluation\x12\x15\n\rmatch_percent\x18\x01 \x01(\x01\x12\x30\n\x0emissing_skills\x18\x02 \x03(\x0b\x32\x18.ml_service.MissingSkill\"M\n\x0cMissingSkill\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0erequired_level\x18\x02 \x01(\x05\x12\x17\n\x0f\x63\x61ndidate_level\x18\x03 \x01(\x05\x32Y\n\x0eResumeAnalyzer\x12G\n\x0e\x45valuateResume\x12\x19.ml_service.ResumeRequest\x1a\x1a.ml_service.ResumeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESUMERESPONSE_FINALLEVELSENTRY']._loaded_options = None
  _globals['_RESUMERESPONSE_FINALLEVELSENTRY']._serialized_options = b'8\001'
  _globals['_RESUMEREQUEST']._serialized_start=32
  _globals['_RESUMEREQUEST']._serialized_end=88
  _globals['_RESUMERESPONSE']._serialized_start=91
  _globals['_RESUMERESPONSE']._serialized_end=270
  _globals['_RESUMERESPONSE_FINALLEVELSENTRY']._serialized_start=220
  _globals['_RESUMERESPONSE_FINALLEVELSENTRY']._serialized_end=270
  _globals['_EVALUATION']._serialized_start=272
  _globals['_EVALUATION']._serialized_end=357
  _globals['_MISSINGSKILL']._serialized_start=359
  _globals['_MISSINGSKILL']._serialized_end=436
  _globals['_RESUMEANALYZER']._serialized_start=438
  _globals['_RESUMEANALYZER']._serialized_end=527
# @@protoc_insertion_point(module_scope)
